<?php

namespace Signa\Models;

use Signa\Helpers\Date;
use Phalcon\Mvc\Model;

/**
 * DentistOrderRecipe
 * 
 * @package Signa\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-10-25, 06:07:59
 */
class DentistOrderRecipe extends Model
{

    protected $id;
    protected $order_id;
    protected $recipe_id;
    protected $parent_id;
    protected $price;
    protected $created_at;
    protected $created_by;
    protected $updated_at;
    protected $updated_by;
    protected $deleted_at;
    protected $deleted_by;
    protected $status;
    protected $status_changed_by;
    protected $status_prev;
    protected $status_changed_at;
    protected $schema_values;



    public function initialize()
    {
        $this->belongsTo('order_id', 'Signa\Models\DentistOrder', 'id', array('alias' => 'DentistOrder'));
        $this->belongsTo('recipe_id', 'Signa\Models\Recipes', 'id', array('alias' => 'Recipes'));
        $this->belongsTo('parent_id', 'Signa\Models\DentistOrderRecipe', 'id', array('alias' => 'ParentOrderRecipe'));
        $this->hasMany('id', 'Signa\Models\DentistOrderRecipeData', 'order_recipe_id', array('alias' => 'DentistOrderRecipeData'));
        $this->hasMany('id', 'Signa\Models\DentistOrderRecipeDelivery', 'dentist_order_recipe_id', array('alias' => 'Delivery'));
        $this->hasMany('id', 'Signa\Models\DentistOrderFile', 'order_recipe_id', array('alias' => 'Files'));
        $this->hasOne('status_changed_by', Users::class, 'id', ['alias' => 'StatusUser']);
        $this->hasOne('status_prev', RecipeStatus::class, 'id', ['alias' => 'StatusPrev']);
        $this->hasOne('status', RecipeStatus::class, 'id', ['alias' => 'StatusCurrent']);

    }

    public function beforeCreate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setCreatedAt(Date::currentDatetime());
        $this->setCreatedBy($user->getId());
    }

    public function beforeUpdate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setUpdatedAt(Date::currentDatetime());
        $this->setUpdatedBy($user->getId());
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Returns the value of field order_id
     *
     * @return integer
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Method to set the value of field order_id
     *
     * @param integer $order_id
     * @return $this
     */
    public function setOrderId($order_id)
    {
        $this->order_id = $order_id;

        return $this;
    }

    /**
     * Returns the value of field recipe_id
     *
     * @return integer
     */
    public function getRecipeId()
    {
        return $this->recipe_id;
    }

    /**
     * Method to set the value of field recipe_id
     *
     * @param integer $recipe_id
     * @return $this
     */
    public function setRecipeId($recipe_id)
    {
        $this->recipe_id = $recipe_id;

        return $this;
    }

    /**
     * Returns the value of field parent_id
     *
     * @return integer
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Method to set the value of field parent_id
     *
     * @param integer $parent_id
     * @return $this
     */
    public function setParentId($parent_id)
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    /**
     * Returns the value of field price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Method to set the value of field price
     *
     * @param double $price
     * @return $this
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Returns the value of field created_by
     *
     * @return integer
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Method to set the value of field created_by
     *
     * @param integer $created_by
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->created_by = $created_by;

        return $this;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field updated_by
     *
     * @return integer
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Method to set the value of field updated_by
     *
     * @param integer $updated_by
     * @return $this
     */
    public function setUpdatedBy($updated_by)
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * Returns the value of field deleted_at
     *
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Method to set the value of field deleted_at
     *
     * @param string $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Returns the value of field deleted_by
     *
     * @return integer
     */
    public function getDeletedBy()
    {
        return $this->deleted_by;
    }

    /**
     * Method to set the value of field deleted_by
     *
     * @param integer $deleted_by
     * @return $this
     */
    public function setDeletedBy($deleted_by)
    {
        $this->deleted_by = $deleted_by;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return int
     */
    public function getStatusChangedBy()
    {
        return $this->status_changed_by;
    }

    /**
     * @param int $status_changed_by
     */
    public function setStatusChangedBy($status_changed_by)
    {
        $this->status_changed_by = $status_changed_by;
    }

    /**
     * @return int
     */
    public function getStatusPrev()
    {
        return $this->status_prev;
    }

    /**
     * @param int $status_prev
     */
    public function setStatusPrev($status_prev)
    {
        $this->status_prev = $status_prev;
    }

    /**
     * @return string
     */
    public function getStatusChangedAt()
    {
        return $this->status_changed_at;
    }

    /**
     * @param string $status_changed_at
     */
    public function setStatusChangedAt($status_changed_at)
    {
        $this->status_changed_at = $status_changed_at;
    }

    /**
     * @return mixed
     */
    public function getSchemaValues()
    {
        return $this->schema_values;
    }

    /**
     * @param mixed $schema_values
     */
    public function setSchemaValues($schema_values)
    {
        $this->schema_values = $schema_values;
    }


    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'dentist_order_recipe';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderRecipe[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderRecipe
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
