<?php

namespace Signa\Models;

use Signa\Helpers\Date;
use Phalcon\Mvc\Model;

/**
 * DentistOrderFile
 * 
 * @package Signa\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-10-25, 06:08:10
 */
class DentistOrderFile extends Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $order_id;

    /**
     *
     * @var integer
     */
    protected $order_recipe_id;

    /**
     *
     * @var integer
     */
    protected $order_note_id;

    /**
     *
     * @var string
     */
    protected $file_name;

    /**
     *
     * @var string
     */
    protected $file_path;

    /**
     *
     * @var string
     */
    protected $file_type;

    /**
     *
     * @var string
     */
    protected $created_at;

    /**
     *
     * @var integer
     */
    protected $created_by;

    /**
     *
     * @var string
     */
    protected $updated_at;

    /**
     *
     * @var integer
     */
    protected $updated_by;

    /**
     *
     * @var string
     */
    protected $deleted_at;

    /**
     *
     * @var integer
     */
    protected $deleted_by;

    public function initialize()
    {
        $this->belongsTo('order_id', 'Signa\Models\DentistOrder', 'id', array('alias' => 'DentistOrder'));
        $this->belongsTo('order_recipe_id', 'Signa\Models\DentistOrderRecipe', 'id', array('alias' => 'DentistOrderRecipe'));
        $this->belongsTo('order_note_id', 'Signa\Models\DentistOrderNotes', 'id', array('alias' => 'DentistOrderNote'));
    }

    public function beforeCreate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setCreatedAt(Date::currentDatetime());
        $this->setCreatedBy($user->getId());
    }

    public function beforeUpdate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setUpdatedAt(Date::currentDatetime());
        $this->setUpdatedBy($user->getId());
    }
    public function softDelete()
    {
        $user = $this->getDI()->getSession()->get('auth');
        $this->setDeletedBy($user->getId());
        $this->setDeletedAt(Date::currentDatetime());
        $this->save();
    }

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field order_id
     *
     * @param integer $order_id
     * @return $this
     */
    public function setOrderId($order_id)
    {
        $this->order_id = $order_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getOrderRecipeId()
    {
        return $this->order_recipe_id;
    }

    /**
     * @param int $order_recipe_id
     */
    public function setOrderRecipeId($order_recipe_id)
    {
        $this->order_recipe_id = $order_recipe_id;
    }

    /**
     * @return int
     */
    public function getOrderNoteId()
    {
        return $this->order_note_id;
    }

    /**
     * @param int $order_note_id
     */
    public function setOrderNoteId($order_note_id)
    {
        $this->order_note_id = $order_note_id;
    }

    /**
     * Method to set the value of field file_name
     *
     * @param string $file_name
     * @return $this
     */
    public function setFileName($file_name)
    {
        $this->file_name = $file_name;

        return $this;
    }

    /**
     * Method to set the value of field file_path
     *
     * @param string $file_path
     * @return $this
     */
    public function setFilePath($file_path)
    {
        $this->file_path = $file_path;

        return $this;
    }

    /**
     * Method to set the value of field file_type
     *
     * @param string $file_type
     * @return $this
     */
    public function setFileType($file_type)
    {
        $this->file_type = $file_type;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field created_by
     *
     * @param integer $created_by
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->created_by = $created_by;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_by
     *
     * @param integer $updated_by
     * @return $this
     */
    public function setUpdatedBy($updated_by)
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * Method to set the value of field deleted_at
     *
     * @param string $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Method to set the value of field deleted_by
     *
     * @param integer $deleted_by
     * @return $this
     */
    public function setDeletedBy($deleted_by)
    {
        $this->deleted_by = $deleted_by;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field order_id
     *
     * @return integer
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Returns the value of field file_name
     *
     * @return string
     */
    public function getFileName()
    {
        return $this->file_name;
    }

    /**
     * Returns the value of field file_path
     *
     * @return string
     */
    public function getFilePath()
    {
        return $this->file_path;
    }

    /**
     * Returns the value of field file_type
     *
     * @return string
     */
    public function getFileType()
    {
        return $this->file_type;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field created_by
     *
     * @return integer
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns the value of field updated_by
     *
     * @return integer
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Returns the value of field deleted_at
     *
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Returns the value of field deleted_by
     *
     * @return integer
     */
    public function getDeletedBy()
    {
        return $this->deleted_by;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'dentist_order_file';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderFile[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderFile
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
