<?php

namespace Signa\Models;

use Signa\Helpers\Date;
use Phalcon\Mvc\Model;

/**
 * DentistOrderRecipe
 * 
 * @package Signa\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-10-25, 06:07:59
 */
class DentistOrderRecipeDelivery extends Model
{

    protected $id;
    protected $dentist_order_id;
    protected $dentist_order_recipe_id;
    protected $recipe_status_id;
    protected $delivery_date;
    protected $delivery_text;
    protected $days;
    protected $part_of_day;
    protected $created_at;
    protected $created_by;
    protected $updated_at;
    protected $updated_by;
    protected $deleted_at;
    protected $deleted_by;

    public function initialize()
    {
        $this->belongsTo('dentist_order_recipe_id', 'Signa\Models\DentistOrderRecipe', 'id', array('alias' => 'DentistOrderRecipe'));
        $this->belongsTo('dentist_order_id', 'Signa\Models\DentistOrder', 'id', array('alias' => 'DentistOrder'));
    }

    public function beforeCreate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setCreatedAt(Date::currentDatetime());
        $this->setCreatedBy($user->getId());
    }

    public function beforeUpdate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setUpdatedAt(Date::currentDatetime());
        $this->setUpdatedBy($user->getId());
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDays()
    {
        return $this->days;
    }

    /**
     * @param mixed $days
     */
    public function setDays($days)
    {
        if ($days == '') {
            $days = null;
        }
        $this->days = $days;
    }

    /**
     * @return mixed
     */
    public function getPartOfDay()
    {
        return $this->part_of_day;
    }

    /**
     * @param mixed $part_of_day
     */
    public function setPartOfDay($part_of_day)
    {
        $this->part_of_day = $part_of_day;
    }

    /**
     * @return mixed
     */
    public function getRecipeStatusId()
    {
        return $this->recipe_status_id;
    }

    /**
     * @param mixed $recipe_status_id
     */
    public function setRecipeStatusId($recipe_status_id)
    {
        if ($recipe_status_id == '') {
            $recipe_status_id = null;
        }
        $this->recipe_status_id = $recipe_status_id;
    }

    /**
     * Returns the value of field dentist_order_recipe_id
     *
     * @return integer
     */
    public function getDentistOrderId()
    {
        return $this->dentist_order_id;
    }

    /**
     * Method to set the value of field dentist_order_id
     *
     * @param integer $dentist_order_id
     * @return $this
     */
    public function setDentistOrderId($dentist_order_id)
    {
        $this->dentist_order_id = $dentist_order_id;

        return $this;
    }

    /**
     * Returns the value of field dentist_order_recipe_id
     *
     * @return integer
     */
    public function getDentistOrderRecipeId()
    {
        return $this->dentist_order_recipe_id;
    }

    /**
     * Method to set the value of field dentist_order_recipe_id
     *
     * @param integer $dentist_order_recipe_id
     * @return $this
     */
    public function setDentistOrderRecipeId($dentist_order_recipe_id)
    {
        $this->dentist_order_recipe_id = $dentist_order_recipe_id;

        return $this;
    }

    /**
     * @return string
     */
    public function getDeliveryDate()
    {
        return $this->delivery_date;
    }

    /**
     * @param string $delivery_date
     */
    public function setDeliveryDate($delivery_date)
    {
        $this->delivery_date = $delivery_date;
    }

    /**
     * @return string
     */
    public function getDeliveryText()
    {
        return $this->delivery_text;
    }

    /**
     * @param string $delivery_text
     */
    public function setDeliveryText($delivery_text)
    {
        $this->delivery_text = $delivery_text;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Returns the value of field created_by
     *
     * @return integer
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Method to set the value of field created_by
     *
     * @param integer $created_by
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->created_by = $created_by;

        return $this;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Returns the value of field updated_by
     *
     * @return integer
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Method to set the value of field updated_by
     *
     * @param integer $updated_by
     * @return $this
     */
    public function setUpdatedBy($updated_by)
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * Returns the value of field deleted_at
     *
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Method to set the value of field deleted_at
     *
     * @param string $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Returns the value of field deleted_by
     *
     * @return integer
     */
    public function getDeletedBy()
    {
        return $this->deleted_by;
    }

    /**
     * Method to set the value of field deleted_by
     *
     * @param integer $deleted_by
     * @return $this
     */
    public function setDeletedBy($deleted_by)
    {
        $this->deleted_by = $deleted_by;

        return $this;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'dentist_order_recipe_delivery';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderRecipe[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderRecipe
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
