<?php

namespace Signa\Models;

use Phalcon\Mvc\Model;
use Signa\Helpers\Date;
use Signa\Libs\DentistOrders as DentistOrderLib;

/**
 * DentistOrder
 *
 * @package Signa\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-10-25, 06:06:53
 */
class DentistOrder extends Model
{
    protected $id;
    protected $code;
    protected $dentist_id;
    protected $dentist_user_id;
    protected $location_id;
    protected $lab_created;
    protected $status;
    protected $password;
    protected $description;
    protected $order_at;
    protected $order_by;
    protected $delivery_by;
    protected $created_at;
    protected $created_by;
    protected $updated_at;
    protected $updated_by;
    protected $deleted_at;
    protected $deleted_by;

    private $statusLabels = array(
        0 => 'Without recipes',
        1 => 'Open',
        2 => 'New',
        3 => 'In progress',
        4 => 'On delivery',
        5 => 'Delivered'
    );

    public function initialize()
    {
        $this->belongsTo('created_by', 'Signa\Models\Users', 'id', array('alias' => 'CreatedBy'));
        $this->belongsTo('updated_by', 'Signa\Models\Users', 'id', array('alias' => 'UpdatedBy'));
        $this->belongsTo('dentist_user_id', 'Signa\Models\Users', 'id', array('alias' => 'DentistUser'));
        $this->belongsTo('dentist_id', 'Signa\Models\Organisations', 'id', array('alias' => 'Dentist'));
        $this->belongsTo('location_id', 'Signa\Models\DentistLocation', 'id', array('alias' => 'DentistLocation'));
        $this->hasOne('id', 'Signa\Models\DentistOrderBsn', 'order_id', array('alias' => 'DentistOrderBsn'));
        $this->hasOne('id', 'Signa\Models\DeliveryNotes', 'order_id', array('alias' => 'DeliveryNote'));
        $this->hasOne('id', 'Signa\Models\DentistOrderData', 'order_id', array('alias' => 'DentistOrderData'));
        $this->hasMany('id', 'Signa\Models\DentistOrderFile', 'order_id', array('alias' => 'DentistOrderFile'));
        $this->hasMany('id', 'Signa\Models\DentistOrderRecipe', 'order_id', array('alias' => 'DentistOrderRecipe'));
        $this->hasManyToMany(
            'id',
            'Signa\Models\DentistOrderRecipe',
            'order_id',
            'recipe_id',
            'Signa\Models\Recipes',
            'id',
            array('alias' => 'Recipes')
        );
    }

    public function beforeCreate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        if($user->Organisation->getOrganisationTypeId() == 4){
            $this->setLabCreated($user->Organisation->getId());
        }
        else {
            $this->setDentistId($user->Organisation->getId());
        }
        $this->setCreatedAt(Date::currentDatetime());
        $this->setCreatedBy($user->getId());
        $this->setStatus(0);
        $this->setCode();
    }

    public function beforeUpdate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setUpdatedAt(Date::currentDatetime());
        $this->setUpdatedBy($user->getId());
    }

    public function softDelete()
    {
        $user = $this->getDI()->getSession()->get('auth');
        $this->setDeletedBy($user->getId());
        $this->setDeletedAt(Date::currentDatetime());
        $this->save();
    }

    public function getTotal()
    {
        $total = 0;
        foreach ($this->DentistOrderRecipe as $orderRecipe) {
            $total += $orderRecipe->getPrice();
        }

        return $total;
    }

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field dentist_id
     *
     * @param integer $dentist_id
     * @return $this
     */
    public function setDentistId($dentist_id)
    {
        $this->dentist_id = $dentist_id;

        return $this;
    }

    /**
     * Method to set the value of field dentist_user_id
     *
     * @param integer $dentist_user_id
     * @return $this
     */
    public function setDentistUserId($dentist_user_id)
    {
        $this->dentist_user_id = $dentist_user_id;

        return $this;
    }

    /**
     * Method to set the value of field location_id
     *
     * @param integer $location_id
     * @return $this
     */
    public function setLocationId($location_id)
    {
        $this->location_id = $location_id;

        return $this;
    }

    /**
     * Method to set the value of field lab_created
     *
     * @param integer $lab_created
     * @return $this
     */
    public function setLabCreated($lab_created)
    {
        $this->lab_created = $lab_created;

        return $this;
    }

    /**
     * Method to set the value of field status
     *
     * @param integer $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Method to set the value of field password
     *
     * @param string $password
     * @return $this
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Method to set the value of field order_at
     *
     * @param string $order_at
     * @return $this
     */
    public function setOrderAt($order_at)
    {
        $this->order_at = $order_at;

        return $this;
    }

    /**
     * Method to set the value of field order_by
     *
     * @param integer $order_by
     * @return $this
     */
    public function setOrderBy($order_by)
    {
        $this->order_by = $order_by;

        return $this;
    }

    /**
     * Method to set the value of field delivery_by
     *
     * @param integer $delivery_by
     * @return $this
     */
    public function setDeliveryBy($delivery_by)
    {
        $this->delivery_by = $delivery_by;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field created_by
     *
     * @param integer $created_by
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->created_by = $created_by;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_by
     *
     * @param integer $updated_by
     * @return $this
     */
    public function setUpdatedBy($updated_by)
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * Method to set the value of field deleted_at
     *
     * @param string $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Method to set the value of field deleted_by
     *
     * @param integer $deleted_by
     * @return $this
     */
    public function setDeletedBy($deleted_by)
    {
        $this->deleted_by = $deleted_by;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field dentist_id
     *
     * @return integer
     */
    public function getDentistId()
    {
        return $this->dentist_id;
    }

    /**
     * Returns the value of field dentist_user_id
     *
     * @return integer
     */
    public function getDentistUserId()
    {
        return $this->dentist_user_id;
    }

    /**
     * Returns the value of field location_id
     *
     * @return integer
     */
    public function getLocationId()
    {
        return $this->location_id;
    }

    /**
     * Returns the value of field lab_created
     *
     * @return integer
     */
    public function getLabCreated()
    {
        return $this->lab_created;
    }

    /**
     * Returns the value of field status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns the value of field password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Returns the value of field order_at
     *
     * @return string
     */
    public function getOrderAt()
    {
        return $this->order_at;
    }

    /**
     * Returns the value of field order_by
     *
     * @return integer
     */
    public function getOrderBy()
    {
        return $this->order_by;
    }

    /**
     * Returns the value of field delivery_by
     *
     * @return integer
     */
    public function getDeliveryBy()
    {
        return $this->delivery_by;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field created_by
     *
     * @return integer
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns the value of field updated_by
     *
     * @return integer
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Returns the value of field deleted_at
     *
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Returns the value of field deleted_by
     *
     * @return integer
     */
    public function getDeletedBy()
    {
        return $this->deleted_by;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'dentist_order';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrder[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrder
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * @param string $code
     */
    public function setCode()
    {
        $this->code = DentistOrderLib::generateCode();
    }

    /**
     * @return string
     */
    public function getStatusLabel()
    {
        return $this->statusLabels[$this->status];
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

}
