<?php

namespace Signa\Models;

use Signa\Helpers\Date;
use Phalcon\Mvc\Model;

/**
 * DentistOrderRecipeData
 * 
 * @package Signa\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-10-25, 06:08:26
 */
class DentistOrderRecipeData extends Model
{

    protected $id;
    protected $order_recipe_id;
    protected $recipe_custom_field_id;
    protected $field_name;
    protected $field_type;
    protected $field_value;
    /**
     * this is original dentist value, even lab will change value we still will know what dentist chose - for edit table
     * @var text
     */
    protected $field_dentist_value;
    protected $custom_price_tariff_id;
    protected $custom_price_type;
    protected $created_at;
    protected $created_by;
    protected $updated_at;
    protected $updated_by;
    protected $deleted_at;
    protected $deleted_by;
    protected $has_lab_check;
    protected $amount;
    protected $tariff_options;

    public function initialize()
    {
        $this->belongsTo('order_recipe_id', 'Signa\Models\DentistOrderRecipe', 'id', array('alias' => 'DentistOrderRecipe'));
        $this->belongsTo('recipe_custom_field_id', 'Signa\Models\RecipeCustomField', 'id', array('alias' => 'RecipeCustomField'));
        $this->belongsTo('custom_price', 'Signa\Models\CodeTariff', 'id', array('alias' => 'Tariff'));
        $this->hasMany('id', 'Signa\Models\DentistOrderRecipeDataOptions', 'dentist_order_recipe_data_id', array('alias' => 'Options'));
    }

    public function beforeCreate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setCreatedAt(Date::currentDatetime());
        $this->setCreatedBy($user->getId());
    }

    public function beforeUpdate()
    {
        $user = $this->getDI()->getSession()->get('auth');

        $this->setUpdatedAt(Date::currentDatetime());
        $this->setUpdatedBy($user->getId());
    }

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field order_recipe_id
     *
     * @param integer $order_recipe_id
     * @return $this
     */
    public function setOrderRecipeId($order_recipe_id)
    {
        $this->order_recipe_id = $order_recipe_id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRecipeCustomFieldId()
    {
        return $this->recipe_custom_field_id;
    }

    /**
     * @param mixed $recipe_custom_field_id
     */
    public function setRecipeCustomFieldId($recipe_custom_field_id)
    {
        $this->recipe_custom_field_id = $recipe_custom_field_id;
    }

    /**
     * Method to set the value of field field_name
     *
     * @param string $field_name
     * @return $this
     */
    public function setFieldName($field_name)
    {
        $this->field_name = $field_name;

        return $this;
    }

    /**
     * Method to set the value of field field_type
     *
     * @param string $field_type
     * @return $this
     */
    public function setFieldType($field_type)
    {
        $this->field_type = $field_type;

        return $this;
    }

    /**
     * Method to set the value of field field_value
     *
     * @param string $field_value
     * @return $this
     */
    public function setFieldValue($field_value)
    {
        $this->field_value = $field_value;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field created_by
     *
     * @param integer $created_by
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->created_by = $created_by;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_by
     *
     * @param integer $updated_by
     * @return $this
     */
    public function setUpdatedBy($updated_by)
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * Method to set the value of field deleted_at
     *
     * @param string $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Method to set the value of field deleted_by
     *
     * @param integer $deleted_by
     * @return $this
     */
    public function setDeletedBy($deleted_by)
    {
        $this->deleted_by = $deleted_by;

        return $this;
    }

    /**
     * Method to set the value of field has_lab_check
     *
     * @param integer $has_lab_check
     * @return $this
     */
    public function setHasLabCheck($has_lab_check)
    {
        $this->has_lab_check = $has_lab_check;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field order_recipe_id
     *
     * @return integer
     */
    public function getOrderRecipeId()
    {
        return $this->order_recipe_id;
    }

    /**
     * Returns the value of field field_name
     *
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * Returns the value of field field_type
     *
     * @return string
     */
    public function getFieldType()
    {
        return $this->field_type;
    }

    /**
     * Returns the value of field field_value
     *
     * @return string
     */
    public function getFieldValue()
    {
        return $this->field_value;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field created_by
     *
     * @return integer
     */
    public function getCreatedBy()
    {
        return $this->created_by;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns the value of field updated_by
     *
     * @return integer
     */
    public function getUpdatedBy()
    {
        return $this->updated_by;
    }

    /**
     * Returns the value of field deleted_at
     *
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Returns the value of field deleted_by
     *
     * @return integer
     */
    public function getDeletedBy()
    {
        return $this->deleted_by;
    }

    /**
     * Returns the value of field has_lab_check
     *
     * @return integer
     */
    public function getHasLabCheck()
    {
        return $this->has_lab_check;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'dentist_order_recipe_data';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderRecipeData[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return DentistOrderRecipeData
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * @return mixed
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @param mixed $amount
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;
    }

    /**
     * @return mixed
     */
    public function getCustomPriceTariffId()
    {
        return $this->custom_price_tariff_id;
    }

    /**
     * @param mixed $custom_price_tariff_id
     */
    public function setCustomPriceTariffId($custom_price_tariff_id)
    {
        if ($custom_price_tariff_id == '') { // fix for DB
            $custom_price_tariff_id = null;
        }
        $this->custom_price_tariff_id = $custom_price_tariff_id;
    }

    /**
     * @return mixed
     */
    public function getCustomPriceType()
    {
        return $this->custom_price_type;
    }

    /**
     * @param mixed $custom_price_type
     */
    public function setCustomPriceType($custom_price_type)
    {
        $this->custom_price_type = $custom_price_type;
    }

    /**
     * @return mixed
     */
    public function getFieldDentistValue()
    {
        return $this->field_dentist_value;
    }

    /**
     * @param mixed $field_dentist_value
     */
    public function setFieldDentistValue($field_dentist_value)
    {
        $this->field_dentist_value = $field_dentist_value;
    }

    /**
     * @return mixed
     */
    public function getTariffOptions()
    {
        return json_decode($this->tariff_options, true);
    }

    /**
     * @param mixed $tariff_options
     */
    public function setTariffOptions($tariff_options)
    {
        $this->tariff_options = json_encode($tariff_options);
    }
}
