<?php

namespace Signa\Models;

/**
 * Discounts
 * 
 * @package Signa\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-07-15, 04:08:08
 */
class Discounts extends \Phalcon\Mvc\Model
{

    const TYPE_ALL = 'ALL';
    const TYPE_CATEGORY = 'CATEGORY';
    const TYPE_GROUP = 'GROUP';

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $discount;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $relative_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $framework_agreement_id;

    public static function remove($id) {
        $entity = static::findFirst($id);
        return $entity->delete();
    }

    public static function calculate($price, $percent) {
        return $price - $price * $percent / 100;
    }

    /**
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id) {
        $this->id = $id;
    }



    /**
     * Method to set the value of field discount
     *
     * @param double $discount
     * @return $this
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * Method to set the value of field relative_id
     *
     * @param integer $relative_id
     * @return $this
     */
    public function setRelativeId($relative_id)
    {
        $this->relative_id = $relative_id;

        return $this;
    }

    /**
     * Method to set the value of field framework_agreement_id
     *
     * @param integer $framework_agreement_id
     * @return $this
     */
    public function setFrameworkAgreementId($framework_agreement_id)
    {
        $this->framework_agreement_id = $framework_agreement_id;

        return $this;
    }

    /**
     * Returns the value of field discount
     *
     * @return double
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * Returns the value of field relative_id
     *
     * @return integer
     */
    public function getRelativeId()
    {
        return $this->relative_id;
    }

    /**
     * Returns the value of field framework_agreement_id
     *
     * @return integer
     */
    public function getFrameworkAgreementId()
    {
        return $this->framework_agreement_id;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {

    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'discounts';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Discounts[]|Discounts|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Discounts|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
