<?php

namespace Signa\Models;
use Phalcon\Mailer\Message;
use Phalcon\Mvc\Model\Resultset;
use Signa\Libs\Convert;

/**
 * FrameworkAgreements
 *
 * @property \Signa\Models\Organisations $Organisation
 * @property \Signa\Models\Discounts Discounts
 * @property \Signa\Models\FilesStorage Files
 * @property \Signa\Models\Notifications Notifications
 *
 * @package Signa\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-07-15, 04:42:40
 */
class FrameworkAgreements extends \Phalcon\Mvc\Model
{

    const ENTITY_RETAIL_PRICE = 'framework_agreement_retail_price_files';
    const ENTITY_AGREEMENT = 'framework_agreement_agreement_files';
    const ENTITY_SUPPORT_APPLICABILITY = 'framework_agreement_support_applicability_files';
    const ENTITY_SLA_APPLICABILITY = 'framework_agreement_sla_applicability_files';
    const ENTITY_ATTACHMENTS = 'framework_agreement_attachments_files';

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $id;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    protected $start_date;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    protected $due_date;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $user_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    protected $reminder;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $supplier_id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    protected $contact_person;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $order_quantity;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $available_training_sessions;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    protected $sla_applicability;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $notes;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    protected $discount_type;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    protected $active;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=true)
     */
    protected $support_applicability;

    /**
     * @var string
     * @Column(type="string", nullable=true)
     */
    protected $support_applicability_text;

    protected $created_at;
    protected $created_by;
    protected $updated_at;
    protected $updated_by;
    protected $deleted_at;
    protected $deleted_by;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->hasOne('supplier_id', Organisations::class, 'id', ['alias' => 'Organisation']);
        $this->hasMany('id', Discounts::class, 'framework_agreement_id', ['alias' => 'Discounts']);
        $this->hasMany('id', FilesStorage::class, 'entity_id', ['alias' => 'Files']);
        $this->hasMany('id', Notifications::class, 'framework_agreement_id', ['alias' => 'Notifications']);
    }

    /**
     * Returned an active Framework agreement for supplier
     *
     * @param int $supplierId
     * @return \Phalcon\Mvc\Model|\Signa\Models\FrameworkAgreements
     */
    public static function getActiveAgreementBySupplier($supplierId) {
        static::checkConflicts($supplierId);

        return static::findFirst([
            'supplier_id = :supplier_id: AND active = 1 AND start_date <= :date: AND due_date >= :date: ',
            'bind' => [
                'supplier_id' => $supplierId,
                'date'        => date('Y-m-d'),
            ]
        ]);
    }

    /**
     * Disable obsolete framework agreements for supplier
     * @param int $supplierId
     */
    public static function checkConflicts($supplierId) {
        try {
            $agreements = static::find([
                'supplier_id = :supplier_id: AND active = 1 AND start_date <= :date: AND due_date >= :date: ',
                'bind' => [
                    'supplier_id' => $supplierId,
                    'date'        => date('Y-m-d'),
                ]
            ]);
            // Check if it single
            if (1 > count($agreements->toArray())) return;

            // if not disable more older agreement by created_at
            /** @var \Signa\Models\FrameworkAgreements $correctAgreement */
            $correctAgreement = $agreements->getFirst();

            // find correct agreement
            /** @var \Signa\Models\FrameworkAgreements $agreement */
            foreach ($agreements as $agreement) {
                if (strtotime($agreement->getCreatedAt()) > strtotime($correctAgreement->getCreatedAt())) {
                    $correctAgreement = $agreement;
                }
            }

            // disable incorrect agreements
            /** @var \Signa\Models\FrameworkAgreements $agreement */
            foreach ($agreements as $agreement) {

                if ($agreement->getId() === $correctAgreement->getId()) continue;

                $agreement->setActive(false);
                $agreement->update();

                // send notification about disable agreement
                $notification = new Notifications();
                $notification->setType(11);
                $notification->setUserId($agreement->getCreatedBy());
                $notification->setSubject('Framework agreement has been disabled');
                $notification->setDescription('<p>The framework agreement has been disabled because a new framework agreement has entered into force.</p>
<p>Framework agreement id: ' . $agreement->getId() . '</p>
<p><a href=\'/signadens/manage/view/' . $agreement->getId() . '\'>View</a> disabled Framework agreement</p>
<p><a href=\'/signadens/manage/view/' . $correctAgreement->getId() . '\'>View</a> current active Framework agreement</p>
');
                $notification->save();
            }
        } catch (\Exception $e) {
            // todo: log errors
        }
    }

    /**
     * @param $entityName
     * @return \Signa\Models\FilesStorage|\Signa\Models\FilesStorage[]
     */
    public function getFiles($entityName) {
        return FilesStorage::find([
            'entity_id = :id: AND entity_name = :entity_name:',
            'bind' => [
                'entity_name' => $entityName,
                'id'          => $this->getId(),
            ]
        ]);
    }

    /**
     * Find an entity that can be edited
     * @param int $id Entity id
     * @return \Phalcon\Mvc\Model|\Signa\Models\FrameworkAgreements
     */
    public static function findEditable($id) {
        return static::findFirst([
            'id = :id: AND start_date >= :date:',
            'bind' => [
                'id'   => $id,
                'date' => date('Y-m-d'),
            ]
        ]);
    }

    public function beforeCreate()
    {
        $this->created_at = date('Y-m-d H:i:s');
    }

    public function beforeUpdate()
    {
        $this->updated_at = date('Y-m-d H:i:s');
    }

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field start_date
     *
     * @param string $start_date
     * @return $this
     */
    public function setStartDate($start_date)
    {
        $this->start_date = $start_date;

        return $this;
    }

    /**
     * Method to set the value of field due_date
     *
     * @param string $due_date
     * @return $this
     */
    public function setDueDate($due_date)
    {
        $this->due_date = $due_date;

        return $this;
    }

    /**
     * Method to set the value of field user_id
     *
     * @param integer $user_id
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Method to set the value of field reminder
     *
     * @param integer $reminder
     * @return $this
     */
    public function setReminder($reminder)
    {
        $this->reminder = $reminder;

        return $this;
    }

    /**
     * Method to set the value of field supplier_id
     *
     * @param integer $supplier_id
     * @return $this
     */
    public function setSupplierId($supplier_id)
    {
        $this->supplier_id = $supplier_id;

        return $this;
    }

    /**
     * Method to set the value of field contact_person
     *
     * @param string $contact_person
     * @return $this
     */
    public function setContactPerson($contact_person)
    {
        $this->contact_person = $contact_person;

        return $this;
    }

    /**
     * Method to set the value of field order_quantity
     *
     * @param string $order_quantity
     * @return $this
     */
    public function setOrderQuantity($order_quantity)
    {
        $this->order_quantity = $order_quantity;

        return $this;
    }

    /**
     * Method to set the value of field available_training_sessions
     *
     * @param string $available_training_sessions
     * @return $this
     */
    public function setAvailableTrainingSessions($available_training_sessions)
    {
        $this->available_training_sessions = $available_training_sessions;

        return $this;
    }

    /**
     * Method to set the value of field sla_applicability
     *
     * @param integer $sla_applicability
     * @return $this
     */
    public function setSlaApplicability($sla_applicability)
    {
        $this->sla_applicability = $sla_applicability;

        return $this;
    }

    /**
     * Method to set the value of field notes
     *
     * @param string $notes
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->notes = $notes;

        return $this;
    }

    /**
     * Method to set the value of field discount_type
     *
     * @param string $discount_type
     * @return $this
     */
    public function setDiscountType($discount_type)
    {
        $this->discount_type = $discount_type;

        return $this;
    }

    /**
     * Method to set the value of field active
     *
     * @param integer $active
     * @return $this
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSupportApplicability() {
        return $this->support_applicability;
    }

    /**
     * @param mixed $support_applicability
     */
    public function setSupportApplicability($support_applicability) {
        $this->support_applicability = $support_applicability;
    }

    /**
     * @return string
     */
    public function getSupportApplicabilityText() {
        return $this->support_applicability_text;
    }

    /**
     * @param string $support_applicability_text
     */
    public function setSupportApplicabilityText(string $support_applicability_text) {
        $this->support_applicability_text = $support_applicability_text;
    }


    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field start_date
     *
     * @return string
     */
    public function getStartDate()
    {
        return \DateTime::createFromFormat('Y-m-d', $this->start_date)->format('d-m-Y');
    }

    /**
     * Returns the value of field due_date
     *
     * @return string
     */
    public function getDueDate()
    {
        return \DateTime::createFromFormat('Y-m-d', $this->due_date)->format('d-m-Y');
    }

    /**
     * Returns the value of field user_id
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Returns the value of field reminder
     *
     * @return integer
     */
    public function getReminder()
    {
        return $this->reminder;
    }

    /**
     * Returns the value of field supplier_id
     *
     * @return integer
     */
    public function getSupplierId()
    {
        return $this->supplier_id;
    }

    /**
     * Returns the value of field contact_person
     *
     * @return string
     */
    public function getContactPerson()
    {
        return $this->contact_person;
    }

    /**
     * Returns the value of field order_quantity
     *
     * @return string
     */
    public function getOrderQuantity()
    {
        return $this->order_quantity;
    }

    /**
     * Returns the value of field available_training_sessions
     *
     * @return string
     */
    public function getAvailableTrainingSessions()
    {
        return $this->available_training_sessions;
    }

    /**
     * Returns the value of field sla_applicability
     *
     * @return integer
     */
    public function getSlaApplicability()
    {
        return $this->sla_applicability;
    }

    /**
     * Returns the value of field notes
     *
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Returns the value of field discount_type
     *
     * @return string
     */
    public function getDiscountType()
    {
        return $this->discount_type;
    }

    /**
     * Returns the value of field active
     *
     * @return integer
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt() {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at) {
        $this->created_at = $created_at;
    }

    /**
     * @return mixed
     */
    public function getCreatedBy() {
        return $this->created_by;
    }

    /**
     * @param mixed $created_by
     */
    public function setCreatedBy($created_by) {
        $this->created_by = $created_by;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt() {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     */
    public function setUpdatedAt($updated_at) {
        $this->updated_at = $updated_at;
    }

    /**
     * @return mixed
     */
    public function getUpdatedBy() {
        return $this->updated_by;
    }

    /**
     * @param mixed $updated_by
     */
    public function setUpdatedBy($updated_by) {
        $this->updated_by = $updated_by;
    }

    /**
     * @return mixed
     */
    public function getDeletedAt() {
        return $this->deleted_at;
    }

    /**
     * @param mixed $deleted_at
     */
    public function setDeletedAt($deleted_at) {
        $this->deleted_at = $deleted_at;
    }

    /**
     * @return mixed
     */
    public function getDeletedBy() {
        return $this->deleted_by;
    }

    /**
     * @param mixed $deleted_by
     */
    public function setDeletedBy($deleted_by) {
        $this->deleted_by = $deleted_by;
    }

    /**
     * @return array|double
     */
    public function getDiscounts() {
        $discounts = $this->getRelated('Discounts');

        if($this->getDiscountType() !== 'ALL') {
            $discountsArray = [];
            /** @var \Signa\Models\Discounts $discount */
            foreach ($discounts as $discount) {
                $discountsArray[$discount->getRelativeId()] = $discount;
            }

            return $discountsArray;
        }

        return $discounts[0];
    }

    /**
     * Set discounts for save
     * @param array $post
     * @param null $discounts
     */
    public function setDiscountsData($post, $discounts = null) {
        $discountType = strtolower($post['agreement']['discount_type']);
        if($discountType == Discounts::TYPE_ALL) $post['discounts'][$discountType] = [$post['discounts'][$discountType]];

        $discountsPost = $post['discounts'][$discountType];

        if(null === $discounts || 0 === count($discounts)) {
            $discounts = [];
            if ($discountType === 'all') {
                $discounts[0] = new Discounts();
                $discounts[0]->discount = $discountsPost['discount'];
            } else {
                foreach ($discountsPost as $key => $item) {
                    $discounts[$key] = new Discounts();
                    $discounts[$key]->discount = $item['discount'];
                    $discounts[$key]->relative_id = @$item['relative_id'];
                }
            }
        } else {
            $newDiscounts = [];
            if($discountType !== 'all') {
                foreach ($discountsPost as $item) {
                    $temp[$item['id']] = $item['discount'];
                }
                $discountsPost = $temp;
                foreach ($discounts as $discount) {
                    $newDiscount = new Discounts();
                    $newDiscount->id = $discount->id;
                    $newDiscount->relative_id = $discount->relative_id;
                    $newDiscount->discount = $discountsPost[$discount->id];
                    $newDiscounts[] = $newDiscount;
                }
            } else {
                $newDiscount = new Discounts();
                $newDiscount->id = $discounts[0]->id;
                $newDiscount->discount = $discountsPost['discount'];
                $newDiscounts[] = $newDiscount;
            }
            $discounts = $newDiscounts;
        }

        $this->Discounts = $discounts;
    }

    /**
     * @param array $discounts
     */
    public function setDiscounts($discounts) {
        $this->Discounts = $discounts;
    }

    /**
     * @return int
     */
    public function startDateDiffWithCurrent() {
        return strtotime($this->start_date) <=> time();
    }
}
